[server]
headless = true
enableCORS = false
address = "0.0.0.0"

# الـ port مش هنكتبه خالص هنا، Railway هيحطه لوحده
# فامسح السطر اللي فيه port = $PORT تمامًا

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
